#ifndef STATUS_H
#define STATUS_H

#define ALL_OK 0
#define IO_ERROR 1
#define INVALID_ARG_ERROR 2
#define NO_FREE_MEM_ERROR 3
#define BAD_PATH_ERROR 4
#define INVALID_FS_SIGNATURE_ERROR 5
#define READ_ONLY_ERROR 6
#define UNIMPLEMENTED_ERROR 7
#define IS_TAKEN_ERROR 8
#define INVALID_FORMAT_ERROR 9

#endif